### PR TITLE
Convert to cabal.project

### PR DESCRIPTION
**Pull request by phadej**
- Move the lib into `containers`
- Move the tests and benchmarks into `containers-tests`
- Make some adjustments so -Whome-modules is happy
- `ln -s` stuff from `containers` to `containers-tests`
  so things work; use containers-tests to be the library under test and
  benchmarking

### CODE REVIEW

**Comment by phadej** [comment]
Well, seems something changed in `master`, but the idea is this.

**Comment by phadej** [comment]
This is one way. Let me think over weekend if I come up with better one.

**Comment by phadej** [comment]
Travis: Green

**Comment by hvriedel** [comment]
The approach looks reasonable to me

**Comment by treeowl** [comment]
Is there a reason to move everything into an `src` directory?

**Comment by phadej** [comment]
`ln -s src` is simpler and more future-proof (if one adds new top-level namespaces).

Also, often enough not having CWD as source directory prevents some unfortunate interactions.

**Comment by phadej** [comment]
I rebased once again. Won't do anymore.

**Comment by treeowl** [comment]
Thanks a lot for all the work. I'll merge, and maybe we'll find a way to cut the remaining redundancy some other year.

**Pull request merged**
