### PR TITLE
Remove strict `compose` versions

### PR DESCRIPTION
**Pull request by sjakobi**
…as discussed in
https://github.com/haskell-unordered-containers/unordered-containers/pull/299#discussion_r471089295.

### CODE REVIEW

**Comment by sjakobi** [comment]
Once this is merged, I think it would be good to make a release in time for GHC 9.0, so users of `compose` are less likely to encounter the differences in strictness.

**Comment by treeowl** [comment]
Do you know the deadline?

**Comment by sjakobi** [comment]
> Do you know the deadline?

Unfortunately I don't. https://gitlab.haskell.org/ghc/ghc/-/issues/18216#note_298165 seems to indicate that the release preparations are ongoing.

@bgamari When would a `containers` release need to happen so it could be included in GHC 9.0.1?

**Review by treeowl — APPROVED** [review]

**Comment by treeowl** [comment]
Do we have enough `map`/`mapMaybe` fusion rules to make the old behavior cheap to recover?

**Comment by sjakobi** [comment]
> Do we have enough `map`/`mapMaybe` fusion rules to make the old behavior cheap to recover?

No idea.

I was wondering how to best convert a lazy map to a strict one by forcing all the values. Is there anything better than `*.Strict.map id`?

**Comment by sjakobi** [comment]
Let's not discuss this in a closed PR though.

**Comment by treeowl** [comment]
`map id` is the best way I know.

**Comment by treeowl** [comment]
Actually, that's wrong.... The nf package has the right stuff for doing it
efficiently. Or a strictifying fold.

**Comment by sjakobi** [comment]
> Actually, that's wrong.... The nf package has the right stuff for doing it
> efficiently. Or a strictifying fold.

What does that look like in practice? Could you give an example?

**Comment by treeowl** [comment]
forceValues :: Map k v -> ()
forceValues = foldl' (flip seq) ()

Looks like I was wrong about nf. I thought it had a type like this:

newtype Shallow a = Shallow a
instance NFData (Shallow a) where
  rnf !_ = ()

With that,

forceValues = rnf . L.map Shallow

where L.map Shallow should be rewritten to a coercion.

**Comment by sjakobi** [comment]
So a `toStrict` function could be defined as

```
toStrict :: Map k v -> Map k v
toStrict m = foldl' (flip seq) () `seq` m
```

Cheers!

**Comment by treeowl** [comment]
Yes, but fusing that definition ... not so easy! Maybe we should actually
offer that toStrict function so we can attach RULES to it.

**Pull request merged**
