### PR TITLE
Try updating CI again

### PR DESCRIPTION
**Pull request by treeowl**

### CODE REVIEW

**Comment by treeowl** [comment]
@sjakobi, I said `--ghc-head`, and it claimed to be generating for `ghc-head`, but ... I don't see a test job for that. Did I do something wrong?

**Comment by treeowl** [comment]
I guess maybe it only looks a prereleases, and there aren't any recent ones?

**Comment by sjakobi** [comment]
Hmm, I'd expect any CLI options to show up in the `REGENDATA` in the header of the generated YAML file, but that option isn't present there…

Frankly, I'm also not sure about the state of GHC HEAD support for GH Actions within haskell-ci.

I'd recommend to do without a GHC HEAD job and instead to consider using a prerelease of GHC 9.6 once it's ready.

Ideally, the GHC folks would take care of testing `containers` with GHC HEAD, anyway. Although I'm not sure what's planned for head.hackage these days.

**Comment by treeowl** [comment]
@sjakobi There was no trace there because I invoked it wrong. However, invoking it right (which I've done now) doesn't change anything but the regeneration line. I guess we'll just wait for the pre-release and hope to get something? Anyway, thanks for the help.

**Pull request merged**
