### PR TITLE
Introduction/tutorial doc improvements.

### PR DESCRIPTION
**Pull request by m-renaud**
- Update titles so that package name is visible in browser tabs
- Fix typo in sequence docs
- Use https://github.com/m-renaud/haddock-autolink
- Update theme (dark grey with green)

Rendered docs can be found at http://m-renaud-haskell-containers.readthedocs.io/en/rtd-use-submodule/

[ci skip]

### CODE REVIEW

**Comment by treeowl** [comment]
What are the consequences of this submodule business?

**Comment by m-renaud** [comment]
Improvements to the autolinker don't need to take place in the containers repo. Also, if other projects end up using it the code doesn't get out of sync (not everyone needs to copy/paste the Sphinx extension).

Also, if you're not modifying the docs you don't need to pull down all the Python code. If you do want to build the container docs locally you need to pull down the submodule code (see contributing.md file changes for exact commands to run).

Read the docs natively supports submodules so it has no visible effect on the docs.

**Comment by treeowl** [comment]
Go ahead and merge then.

**Comment by m-renaud** [comment]
Will do! I think there are a few more css changes I need to make for a consistent theme on mobile first.

**Pull request merged**
