### PR TITLE
Fix performance of Data.Sequence.filter (fixes #176)

### LINKED ISSUE #176: Data.Sequence filter performance
The following is a criterion benchmark of a simple filter on [Int] and Seq Int.  The [Int] demonstrates linear complexity in the length of the list and Seq Int appears to be quadratic.  (Complete results at end)

[2.1x, 3.2x, 14x]  of List for length = (100,1000,10000)

Tested LTS 4.1 (version 5.6.1) and current versions 5.7.1
ghc -O3

Q.1  Is this what is expected?  If not can you identify error in test procedure?
Q.2  What other Data.Sequence functions will underperform equivalent List functions ?
Q.3  Are there any significant improvements planned relating to GHC 8.01+ ?

Thanks!

--------------------------------------------------------------------------------

{-# LANGUAGE FlexibleContexts, ScopedTypeVariables #-}

import Criterion.Main
import qualified Data.List as L
import qualified Data.Sequence as S

nSeq::IO (S.Seq Int, S.Seq Int, S.Seq Int)
nSeq = return (S.fromList [1..100], S.fromList [1..1000], S.fromList [1..10000])

nList::IO ([Int],[Int],[Int])
nList = return ([1..100],[1..1000],[1..10000])

fL::[Int] -> [Int]
fL =  L.filter ( > (50 :: Int))

fS::S.Seq Int-> S.Seq Int
fS =  S.filter ( > (50 :: Int))

main :: IO ()
main = defaultMain [
        env nList $ \ ~(a,b,c) ->
             bgroup "List Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fL a
               , bench "filter 1000"   $ nf fL b
               , bench "filter 10000"  $ nf fL c
               ]
          ]
         , env nSeq $ \ ~(a,b,c) ->
             bgroup "Seq Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS a
               , bench "filter 1000"   $ nf fS b
               , bench "filter 10000"  $ nf fS c
               ]
          ]
        ]

--------------------------------------- Results ------------------------------------

benchmarking List Int/filter/filter 100
time                 1.007 μs   (985.9 ns .. 1.024 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 995.5 ns   (974.2 ns .. 1.016 μs)
std dev              70.35 ns   (57.38 ns .. 93.81 ns)
variance introduced by outliers: 80% (severely inflated)

benchmarking List Int/filter/filter 1000
time                 13.34 μs   (13.06 μs .. 13.60 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 13.42 μs   (13.15 μs .. 13.68 μs)
std dev              880.3 ns   (745.9 ns .. 1.101 μs)
variance introduced by outliers: 72% (severely inflated)

benchmarking List Int/filter/filter 10000
time                 137.2 μs   (134.4 μs .. 139.7 μs)
                     0.996 R²   (0.994 R² .. 0.998 R²)
mean                 136.3 μs   (133.9 μs .. 139.2 μs)
std dev              9.450 μs   (7.973 μs .. 11.17 μs)
variance introduced by outliers: 67% (severely inflated)

benchmarking Seq Int/filter/filter 100
time                 1.928 μs   (1.905 μs .. 1.953 μs)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 1.927 μs   (1.890 μs .. 1.965 μs)
std dev              123.6 ns   (101.5 ns .. 149.5 ns)
variance introduced by outliers: 75% (severely inflated)

benchmarking Seq Int/filter/filter 1000
time                 42.22 μs   (41.39 μs .. 43.11 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 42.32 μs   (41.59 μs .. 43.04 μs)
std dev              2.512 μs   (2.086 μs .. 3.078 μs)
variance introduced by outliers: 64% (severely inflated)

benchmarking Seq Int/filter/filter 10000
time                 1.776 ms   (1.739 ms .. 1.822 ms)
                     0.996 R²   (0.994 R² .. 0.997 R²)
mean                 1.823 ms   (1.794 ms .. 1.856 ms)
std dev              107.7 μs   (91.41 μs .. 139.2 μs)
variance introduced by outliers: 44% (moderately inflated)

### PR DESCRIPTION
**Pull request by snoyberg**
Pinging @lwdye and @chrisdone

### CODE REVIEW

**Comment by treeowl** [comment]
What do your benchmarks say (and what are they)? Details, please?

**Comment by snoyberg** [comment]
The benchmarks are available in #176.

**Comment by treeowl** [comment]
The reporter of #176 indicated that the `foldl'` implementation worked best. You've chosen a different one. Can you explain/support that?

**Comment by treeowl** [comment]
I'm not trying to be difficult; I'm just trying to understand, and I know Milan likes this sort of info.

**Comment by snoyberg** [comment]
Oh, my mistake, there was a miscommunication about that then. I'll run those now.

**Comment by snoyberg** [comment]
I'm glad you asked, not only was this implementation not covered before, but it's actually slower:

https://gist.github.com/snoyberg/59942fcf341805a16e6f040d12edd70c

I'll update the implementation, thanks for the catch.

**Comment by snoyberg** [comment]
Proper implementation pushed.

**Comment by treeowl** [comment]
For the sake of discussion, what about this idea? Traverse the sequence, building a bit vector representing the locations that will be included as well as counting them. Then build the result sequence from the top down using `splitMap`. The bit vector (a sequence of `Word64`) will be too compact to worry about, and its working end can be kept separate to unbox.

**Comment by snoyberg** [comment]
I don't have enough knowledge of the internals of the data structure to meaningfully comment (and unfortunately don't have time to investigate right now). My general comment though would be not to let the perfect be the enemy of the good: @lwdye's fixes already improve performance significantly.

**Comment by treeowl** [comment]
The idea I just suggested is incomplete. We'd have to force the whole result structure to avoid potential memory leaks. That's not so attractive.

**Comment by treeowl** [comment]
Yes, let's go with lwdye's implementation for now and think more later.

**Comment by foxik** [comment]
@snoyberg Thanks for the patch and for dealing with an opened issue #176!

@treeowl Thanks for nice moderation of the discussion :-)

Cheers,
Milan

**Comment by chrisdone** [comment]
Excellent!

**Pull request merged**
