### PR TITLE
returning Nil on empty IntMap as done in corresponding functions for Map

### LINKED ISSUE #1061: updateMax Map/IntMap discrepancy
`updateMax`, `updateMaxWithKey`, `updateMin`, `updateMinWithKey` for lazy and strict IntMap do not agree with Map.

IntMap errors on an empty map:

https://github.com/haskell/containers/blob/7e7ce15704dce68f67d5e0813ae442993e55b128/containers/src/Data/IntMap/Internal.hs#L2180-L2189

Map simply returns the empty map:

https://github.com/haskell/containers/blob/7e7ce15704dce68f67d5e0813ae442993e55b128/containers/src/Data/Map/Internal.hs#L1744-L1749

The better option is that IntMap also returns an empty map.

---

Historical note: The Map behavior has been so since it was added in bbbba97cbcf12039810533e3a2daf2eefdefe7f0. `updateMax` and friends for IntMap were added a bit later in 1a2cf0f6d9cfddb272af43653915094ef519caa8.

### PR DESCRIPTION
**Pull request by kushagarr**
Closes #1061

@meooow25

### CODE REVIEW

**Review by treeowl — CHANGES_REQUESTED** [review]
Please adjust the property tests accordingly.

**Comment by meooow25** [comment]
Thanks for the PR. Your change seems fine, but as mentioned above please update/add property tests for affected functions. These will be in `containers-tests/intmap-properties.hs`.

**Comment by treeowl** [comment]
@meooow25 , it's obviously not an issue for this PR, but it looks like we only have unit tests for these and many other `IntMap` functions, and no property tests. That's no good!

**Comment by kushagarr** [comment]
So, what is it that I should be doing here, 
If I take `updateMinWithKey` as an example, I see only one `Assertion` called `test_updateMinWithKey` in `containers-tests/tests/intmap-properties.hs`.

Should I just update that assertion to have this change also included in that or you want me to add property tests for this as well.
FYI, Although I have read about tests and property tests in Haskell, I haven't really written them in Haskell before, So please bear with me and guide me if I make mistakes.

**Comment by meooow25** [comment]
I took at look at the tests we have. You could add a new unit test for the empty map case in `test_updateMinWithKey`, `test_updateMaxWithKey`, etc. That's good enough for this PR.
Otherwise, if you want to add new property tests for these functions, it would be very helpful. Let us know if you need any help.

> ...but it looks like we only have unit tests for these and many other `IntMap` functions, and no property tests. That's no good!

Yes that's not ideal, we should look into having property tests for everything.

**Comment by treeowl** [comment]
> Not able to come up with property tests yet, apologies. I need more time may be.

Don't worry about that. @meooow25 opened a new issue to deal with that.

**Review by treeowl — APPROVED** [review]

**Comment by meooow25** [comment]
Thanks!

**Pull request merged**
