### PR TITLE
fix type naming consistency

### PR DESCRIPTION
**Pull request by infinity0**

### CODE REVIEW

**Comment by treeowl** [comment]
What does this commit have to do with type naming? What is it for?

**Comment by infinity0** [comment]
The file being changed contains some code for strict and lazy versions of IntMap, but mixes up invocation of functions from strict vs lazy modules. This commit fixes that.

**Comment by treeowl** [comment]
Could you improve the commit message? Otherwise, looks good.

**Comment by infinity0** [comment]
Sure, how about 75c1e92 ?

**Review by sjakobi — APPROVED** [review]
Thanks!

**Pull request merged**
