### PR TITLE
Fix -Wmissing-home-modules warnings

### LINKED ISSUE #434: Building the containers tests on GHC 8.2.1 is especially noisy due to -Wmissing-home-modules
On a recent build of the `containers` test suites using GHC 8.2.1, I encountered a veritable wall of warnings that were entirely due to `-Wmissing-home-modules`:

```
$ cabal test
Preprocessing test suite 'seq-properties' for containers-0.5.10.2..
Building test suite 'seq-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Sequence
                                                                                                 Data.Sequence.Internal
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Sequence
                                                                                                 Data.Sequence.Internal
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strict-properties' for containers-0.5.10.2..
Building test suite 'intmap-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strictness-properties' for containers-0.5.10.2..
Building test suite 'map-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'bitqueue-properties' for containers-0.5.10.2..
Building test suite 'bitqueue-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
Preprocessing test suite 'map-lazy-properties' for containers-0.5.10.2..
Building test suite 'map-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Merge.Lazy
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Merge.Lazy
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strictness-properties' for containers-0.5.10.2..
Building test suite 'intmap-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-properties' for containers-0.5.10.2..
Building test suite 'intset-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-lazy-properties' for containers-0.5.10.2..
Building test suite 'intmap-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strict-properties' for containers-0.5.10.2..
Building test suite 'map-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Merge.Strict
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Merge.Strict
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-strictness-properties' for containers-0.5.10.2..
Building test suite 'intset-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'deprecated-properties' for containers-0.5.10.2..
Building test suite 'deprecated-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap
                                                                                                 Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Map
                                                                                                 Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap
                                                                                                 Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Map
                                                                                                 Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'set-properties' for containers-0.5.10.2..
Building test suite 'set-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Running 12 test suites...
```

This makes it quite difficult to see actual, substantive warnings that might appear. We should squash these warnings, either by adding the missing modules to `other-modules` in the right places or by suppressing them with `-Wno-missing-home-modules`.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #434.

### CODE REVIEW

**Comment by treeowl** [comment]
I tried to fix this thing up, but goofed something up. Can you please rebase?

**Comment by RyanGlScott** [comment]
Done.

**Comment by treeowl** [comment]
Why do so many modules need to be listed so many places? Is there some way to restructure things to avoid this?

**Comment by RyanGlScott** [comment]
Unfortunately, this is an annoying problem that many core libraries like `containers` face. What one would like to do is list `containers` as a library dependency in each test suite and benchmark, which would obviate the need to duplicate all of these `other-modules`. But `containers`' test suites and benchmarks depend on libraries which themselves depend on `containers`. For apparently technical reasons, this prevents us from listing `containers` as a library dependency there, because `Cabal` would be confused as to whether to link against the version of `containers` used to build the dependencies, or the version of `containers` you're building from source. (See https://github.com/haskell/cabal/issues/4087 for an attempt to fix this issue in `Cabal`.)

Thus, we can't list `containers` as a library dependency, which means that we pretty much have to duplicate the `other-modules` for now. (A possible workaround for this in the future would be to list every thing in `other-modules` in a [`Cabal` common stanza](https://github.com/haskell/cabal/pull/4751).)

**Comment by treeowl** [comment]
Thanks.

**Pull request merged**
