### PR TITLE
fix typos and reword

### PR DESCRIPTION
**Pull request by askeblad**
src/Data/Sequence/Internal.hs

### CODE REVIEW

**Comment by askeblad** [comment]
@treeowl

https://github.com/haskell/containers/pull/824#issuecomment-1092027904

**Comment by askeblad** [comment]
@treeowl

can you merge

**Comment by treeowl** [comment]
Thanks!

**Comment by askeblad** [comment]
[sortOn Functions](https://github.com/haskell/containers/blob/master/containers/src/Data/Sequence/Internal/sorting.md#sorton-functions)

should this read comparing

containers/src/Data/Sequence/Internal/sorting.md

`sortOn f = fmap snd . sortBy (conparing fst) . fmap (\x -> (f x, x))`

**Comment by treeowl** [comment]
Indeed.

**Pull request merged**
