### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by t3hmrman**
"addional" -> "additional"

### CODE REVIEW

**Comment by m-renaud** [comment]
Thanks for the fix! I'll push the changes to readthedocs today :)

**Comment by m-renaud** [comment]
New docs have been built and pushed.

**Comment by t3hmrman** [comment]
No problem, thank you for contributing to the guide! Read all the way through it last week :)

**Comment by m-renaud** [comment]
Glad you found it useful :) Let me know if you have any other feedback on it!

**Pull request merged**
