### PR TITLE
Bump CI to GHC 9.0.2 and 9.2.2; reenable benchmarks for GHC 9.2

### PR DESCRIPTION
**Pull request by andreasabel**
Bump CI to GHC 9.0.2 and 9.2.2; reenable benchmarks for GHC 9.2.
Seems like `gauge` now builds on GHC 9.2.

### CODE REVIEW

**Comment by treeowl** [comment]
Youch. It looks like a dependency has incorrect bounds.

**Comment by andreasabel** [comment]
GHC 9.2.2 CI fails (https://github.com/haskell/containers/runs/6198546742?check_suite_focus=true#step:17:122):
```
Preprocessing library for ghc-heap-9.2.1..
compiling /__w/containers/containers/dist-newstyle/build/x86_64-linux/ghc-9.2.2/ghc-heap-9.2.1/build/GHC/Exts/Heap/FFIClosures_ProfilingDisabled_hsc_make.c failed (exit code 1)
...
error: In file included from /__w/containers/containers/dist-newstyle/build/x86_64-linux/ghc-9.2.2/ghc-heap-9.2.1/build/GHC/Exts/Heap/FFIClosures_ProfilingDisabled_hsc_make.c:1:0:
FFIClosures_ProfilingDisabled.hsc: In function ‘main’:
FFIClosures_ProfilingDisabled.hsc:81:16: error: ‘BlockedOnIOCompletion’ undeclared (first use in this function); did you mean ‘BlockedOnDoProc’?
...
cabal-3.6.2.0: Failed to build ghc-heap-9.2.1 (which is required by containers-tests-0).
```
Same error discussed at:
- https://github.com/digital-asset/ghc-lib/issues/354

**Comment by treeowl** [comment]
I don't follow that discussion. Do we need to file a ticket for `ghc-heap` to get bounds fixed?

**Comment by andreasabel** [comment]
Well, shouldn't GHC 9.2.2 use `ghc-heap-9.2.2`, rather than `ghc-heap-9.2.1`?  (Only the latter is published on hackage, but I have ghc-heap-9.2.2 shipped with my GHC 9.2.2, locally on my machine.)
Maybe the problem is that `ghc-heap` isn't tied to the `installed` version?, see:
https://github.com/haskell/containers/blob/b71393038c3c6dac886437f0563e310cd4a6b009/cabal.haskell-ci#L12-L14
(But this relaxation came with a reason...)

**Comment by treeowl** [comment]
Yes, we need the right version, which isn't there. I think there are two problems:

1. `ghc-heap-9.2.2` isn't on Hackage.
2. `ghc-heap-9.2.1` needs a tighter upper bound for `base`.

**Comment by andreasabel** [comment]
> * `ghc-heap-9.2.1` needs a tighter upper bound for `base`.

Indeed, `cabal get ghc-heap-9.2.1 && cd ghc-heap-9.2.1 && cabal build -w ghc-9.2.2` fails with just our error:
```
FFIClosures_ProfilingDisabled.hsc:81:16: error: use of undeclared identifier 'BlockedOnIOCompletion'
```

I can make `ghc-heap-9.2.1` unbuildable with the bound `base < 4.16.1`:
```
$ cabal build --constraint='base < 4.16.1'
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
...
[__0] trying: ghc-heap-9.2.1
[__1] next goal: base (dependency of ghc-heap)
[__1] rejecting: base-4.16.1.0/installed-4.16.1.0, base-4.16.1.0 (constraint
from command line flag requires <4.16.1)
```

**Comment by andreasabel** [comment]
> 1. `ghc-heap-9.2.2` isn't on Hackage.

Requested publication at: https://gitlab.haskell.org/ghc/ghc/-/issues/21439

> 2. `ghc-heap-9.2.1` needs a tighter upper bound for `base`.

Fixed at: https://hackage.haskell.org/package/ghc-heap-9.2.1/revisions/

**Comment by treeowl** [comment]
Thanks!

**Comment by mpickering** [comment]
I am not sure why `ghc-heap` not being on hackage is an issue, it's installed locally so you should make sure to choose a build plan which uses ghc-heap from the global package db.

**Comment by andreasabel** [comment]
> I am not sure why `ghc-heap` not being on hackage is an issue, it's installed locally so you should make sure to choose a build plan which uses ghc-heap from the global package db.

I am not sure either, but `ghc-heap` depends on `containers`, so maybe the idea is to test `containers` also via its use in `ghc-heap`?  (@treeowl, please correct me.)

**Comment by treeowl** [comment]
@mpickering, I'm not sure in this case; it might be okay to use the installed one. @andreasabel Could you try that and see if it works? I'd like to try to get a release out shortly.

**Comment by andreasabel** [comment]
Nope, fails for GHC 9.2.2 as well: (ping @mpickering)
https://github.com/haskell/containers/runs/6198546742?check_suite_focus=true : 
```
[__2] rejecting: ghc-heap-9.2.2/installed-9.2.2 (package is broken, missing dependency containers-0.6.5.1)
```

**Comment by mpickering** [comment]
Ah right then I think you analysis about ghc-heap being missing from hackage is correct. I will chase up the upload.

**Comment by mpickering** [comment]
ghc-heap-9.2.2 is now released, can you check that it works for you?

**Comment by andreasabel** [comment]
Thanks @mpickering!  Works now.

**Comment by treeowl** [comment]
Opened another PR to get git to cooperate. Sorry.

**Comment by andreasabel** [comment]
Continued in 
- #846.

**Pull request closed without merging**
