### PR TITLE
Fix haddocks

### PR DESCRIPTION
**Pull request by ggreif**
for `mapAccumRWithKey`

### CODE REVIEW

**Comment by ggreif** [comment]
I suggest to squash those two commits, or should I?

**Comment by ggreif** [comment]
> Cheers!

You'll merge?

**Comment by sjakobi** [comment]
> @sjakobi You'll merge?

@ggreif I'd like to, but I don't have the necessary permissions.

@treeowl Could you possibly give me commit bits? I promise not to use them without appropriate coordination with you or other maintainers.

**Comment by treeowl** [comment]
I've emailed Herbert. I hope he's still the one who adds people to the
Haskell "organization", a prerequisite.

**Comment by sjakobi** [comment]
> I've emailed Herbert. I hope he's still the one who adds people to the
> Haskell "organization", a prerequisite.

Many thanks, also to @hvr, for adding me! :)

**Pull request merged**
