### PR TITLE
Remove 'stability' annotations

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes https://github.com/haskell/containers/issues/389.

### CODE REVIEW

**Comment by treeowl** [comment]
I'm super-tempted to change these all to "metastable", but I think your way is the right one. *sigh*

**Comment by sjakobi** [comment]
> I'm super-tempted to change these all to "metastable", but I think your way is the right one. sigh

[Here](http://stackoverflow.com/questions/3841218/conventions-for-stability-field-of-cabal-packages)'s a bit of discussion on the purpose of this field. I think that, because the field has been misused so often, people wouldn't know how to interpret a `stability: metastable` annotation.

**Comment by treeowl** [comment]
I was joking about metastable.

**Comment by treeowl** [comment]
Thanks for the patch.

**Pull request merged**
