### PR TITLE
Add MonadFix instance for Data.Tree

### PR DESCRIPTION
**Pull request by treeowl**
This is based on an instance for a somewhat more general type
by G. Allais.
See [MonadTree.hs](https://gist.github.com/gallais/4c59b949c743c0a85cab55dcb73aaf7c).

### CODE REVIEW

**Comment by treeowl** [comment]
@gallais Your review would be greatly appreciated.

**Comment by treeowl** [comment]
In particular, I have no idea how to go about checking the `MonadFix` laws for this instance. Anything beyond the purity law seems to get messy.

**Comment by treeowl** [comment]
@ocharles, actually, I see you were also involved in this. Did you or @gallais figure it out, or do both deserve credit? And do you think it's law-abiding?

**Comment by ocharles** [comment]
https://gist.github.com/ocharles/9b6fb71669de4533373a9c7f1f3ce8f9 appears to work, but I haven't checked the laws hold.

**Comment by ocharles** [comment]
In regards to credit, @gallais deserves all the credit, for sure.

**Comment by gallais** [comment]
As mentioned in [the original discussion](https://stackoverflow.com/questions/47833188/can-a-monadic-rose-tree-have-a-monadfix-instance) this is based off of the intuition I built up reading the `MonadFix` instance for `[]`.

Your implementation looks like what I would have written but I don't think I'm qualified to say whether this is a valid `MonadFix` instance. I'll try to see if I can prove (some of) the laws.

**Comment by treeowl** [comment]
@gallais intuition from the list instance suggests that the purity, sliding, and nesting laws should hold for the same reason they do for lists (whatever that may be). The one that really smells like it needs careful proving is left  shrinking, since it gets into the details of the `mfix`/`>>=` interaction.

**Pull request merged**
