### PR TITLE
containers-tests: Enable -Werror for recent GHC versions

### PR DESCRIPTION
**Pull request by sjakobi**
…and fix a bunch of warnings.

### CODE REVIEW

**Comment by treeowl** [comment]
I'd prefer to prefix variable names with `_` rather than replacing them altogether. That makes it easier to see what's being ignored and keep track of what argument is what.

**Comment by sjakobi** [comment]
@treeowl Good point. Fixed.

**Comment by treeowl** [comment]
I'm going to let you and @gereeter decide whether this gets merged now or integrated into his PR.

**Comment by sjakobi** [comment]
I think this is useful on its own – the warnings are somewhat annoying during development.

@gereeter, any reasons not to merge this already?

**Comment by gereeter** [comment]
> @gereeter, any reasons not to merge this already?

No, you should be good. I'll appreciate not worrying that the warnings mean I did something wrong every time it decides to recompile the non-`IntMap` modules.

**Comment by treeowl** [comment]
Thanks!

**Comment by sjakobi** [comment]
Unfortunately this broke the build on 32-bit systems:

```

libraries/containers/containers/src/Data/IntSet/Internal.hs:1610:19: error:
    Not in scope: data constructor ‘I#’
    Perhaps you meant one of these:
      ‘GHCExts.I#’ (imported from GHC.Exts),
      ‘GHCExts.C#’ (imported from GHC.Exts),
      ‘GHCExts.D#’ (imported from GHC.Exts)
    Perhaps you want to add ‘I#’ to the import list in the import of
    ‘GHC.Exts’
    (libraries/containers/containers/src/Data/IntSet/Internal.hs:221:1-23).
     |
1610 |   where unboxInt (I# i) = i
     |                   ^^
```

I think this should fix it but I'll test it first:

```diff
--- a/containers/src/Data/IntSet/Internal.hs
+++ b/containers/src/Data/IntSet/Internal.hs
@@ -221,6 +221,8 @@ import Text.Read
 import GHC.Exts (build)
 #if !MIN_VERSION_base(4,8,0)
 import GHC.Exts (Int(..), indexInt8OffAddr#)
+#elif WORD_SIZE_IN_BITS!=64
+import GHC.Exts (Int(..))
 #endif
 #if __GLASGOW_HASKELL__ >= 708
 import qualified GHC.Exts as GHCExts
```

Maybe I can clean up this mess of imports and CPP a bit too…

**Pull request merged**
