### PR TITLE
Fix build paths in gitignore

### PR DESCRIPTION
**Pull request by alexfmpe**
Current .gitignore isn't matching these dirs
```
containers-tests/dist-newstyle/
containers-tests/dist/
containers/dist-newstyle/
containers/dist/
```

### CODE REVIEW

**Comment by treeowl** [comment]
Is there any risk someone might want a directory named `dist` somewhere in the source tree? Or is that too far-fetched?

**Comment by alexfmpe** [comment]
It would be a risky thing to do in a haskell repo and it being in gitignore would likely stand out as when one tried to add it to version control. That said, I'm not opposed to hardcoding `containers` and `containers-tests` instead of `**`. Would that be better?

**Comment by treeowl** [comment]
No, I think it's probably fine. If we run into trouble we'll deal with it then.

**Comment by treeowl** [comment]
Thanks.

**Pull request merged**
