### PR TITLE
Mention Data.IntSet.alterF in changelog

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by treeowl** [comment]
While you're at it, could you mention Li-Yao's work on the comments for `Data.Sequence` `liftA2`?

**Comment by sjakobi** [comment]
I thought that's kind of covered in this bit:

> Make (<*) for Data.Sequence incrementally asymptotically optimal. This finally completes the task, begun in December 2014, of making all the Applicative methods for sequences asymptotically optimal even when their results are consumed incrementally. Many thanks to Li-Yao Xia and Bertram Felgenhauer for helping to clean up and begin to document this rather tricky code.

Should I add him in the documentation bullet point too?

**Comment by treeowl** [comment]
He documented `liftA2` code as well as cleaning and documenting `<*` code. I think it deserves a separate mention, but maybe the release notes would be a better place for that.

**Comment by sjakobi** [comment]
> He documented `liftA2` code as well as cleaning and documenting `<*` code.

Oh, yes. I had mixed that up.

**Pull request merged**
