### PR TITLE
Fix typo in error message for minimum

### PR DESCRIPTION
**Pull request by charles-cooper**
Fixes https://github.com/haskell/containers/issues/349

### CODE REVIEW

**Comment by charles-cooper** [comment]
Hmm, what do you dislike about the error message? It seems clear to me.

**Comment by treeowl** [comment]
Data.Foldable.Map isn't a real thing.

**Comment by charles-cooper** [comment]
@treeowl how does the new message look?

**Comment by treeowl** [comment]
I prefer to err on the side of verbosity. How do you feel about this?

```haskell
foldableError :: String -> String -> String -> a
foldableError longname name meth = error $
  "Data.Foldable." ++ meth ++ " (for " ++ longname ++"): empty " ++ name
```

**Comment by charles-cooper** [comment]
so for example this might be called as `foldableError "Data.Map.Lazy" "map" "maximum"`?

**Comment by treeowl** [comment]
That was my thought.

**Comment by charles-cooper** [comment]
I didn't see a good place to stick `foldableError` so I just wrote out the four error messages

**Comment by treeowl** [comment]
Thanks. That looks good. We probably want to do something similar for the rest of the package.

**Pull request merged**
