### PR TITLE
Add Data.IntSet.alterF

### LINKED ISSUE #719: Data.IntSet.alterF?
I noticed that we didn't add an `IntSet` version of `alterF` in #682. 

The type should be

```haskell
alterF :: Functor f => (Bool -> f Bool) -> Key -> IntSet -> f (IntSet)
```

A trivial implementation using `delete` and `insert` should probably be good enough.

Is it worth adding?

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #719.

### CODE REVIEW

**Comment by sjakobi** [comment]
I've copied rules and docs from `Data.Set` and added property tests checking again the `Set` version.

This should be ready for review now.

**Comment by sjakobi** [comment]
Apparently I'll need to add a bit of CPP in the testsuite:

```
tests/intset-properties.hs:76:22:
    No instance for (Show (Const Bool Bool))
      arising from a use of ‘testProperty’
    In the expression:
      testProperty "prop_alterF_const" prop_alterF_const
    In the first argument of ‘defaultMain’, namely
      ‘[testCase "lookupLT" test_lookupLT,
        testCase "lookupGT" test_lookupGT,
        testCase "lookupLE" test_lookupLE,
        testCase "lookupGE" test_lookupGE, ....]’
    In the expression:
      defaultMain
        [testCase "lookupLT" test_lookupLT,
         testCase "lookupGT" test_lookupGT,
         testCase "lookupLE" test_lookupLE,
         testCase "lookupGE" test_lookupGE, ....]
```

(That's with 7.8)

**Comment by treeowl** [comment]
Or you could use  `Bool` there and construct the `Const` within. That should be pretty clear, right?

**Comment by sjakobi** [comment]
Good idea, @treeowl! :)

**Comment by treeowl** [comment]
@emilypi, I thought you were going to be working on `unordered-containers`. We have enough people to manage tickets here, though of course substantive contributions are always welcome.

**Comment by emilypi** [comment]
I was looking at both :)

**Comment by treeowl** [comment]
@emilypi, look, comment, contribute, etc., all you like, but review requests, PR approvals, and such are more noise than we need here.

**Comment by sjakobi** [comment]
FWIW, I appreciate both your reviews, @emilypi and @treeowl! :)

**Pull request merged**
