### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by m-renaud**
It's not immediately clear how to build and run the tests when making contributions to this project. Cabal-install is unable to find a consistent set of dependencies when I tried so this doc advises using Stack.

### CODE REVIEW

**Comment by treeowl** [comment]
I'd rather not merge this until we have good instructions for cabal. I've definitely made it work myself (recently!) so we can surely do this. If you want to give it another go, you may try wading into the Travis CI script to see how that handles it.

**Comment by m-renaud** [comment]
For sure, I'll see if I have some time in the next couple days to take a look.

**Comment by m-renaud** [comment]
Updated with complete instructions for cabal-install.

**Comment by treeowl** [comment]
Thanks!

**Comment by treeowl** [comment]
Actually, there are a few things I'd like added. Do you think you could do that?

1. Add instructions for rubbing the cabal benchmark suite, including installing the dependencies.
2. Urge contributors to run the benchmarks when changing implementations, and to include benchmark results in their commit messages.
3. Ask that contributors document non-trivial changes in the change log, particularly if they change the API or affect performance. I always try to keep the log up to date, but I sometimes miss things.

**Comment by m-renaud** [comment]
Sure. I'll open a new pull request when I have a few minutes.

**Pull request merged**
