### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by askeblad**
containers-tests/tests/IntSetValidity.hs
containers/src/Data/Set/Internal.hs
containers/src/Utils/Containers/Internal/BitQueue.hs

### CODE REVIEW

**Comment by askeblad** [comment]
@treeowl

can you merge

**Comment by treeowl** [comment]
Thanks!

**Comment by askeblad** [comment]
@tibbe

constraint ?
constraining ?

**Comment by treeowl** [comment]
It should say "uses an (Ix i) constraint".

**Comment by askeblad** [comment]
thamks

**Pull request merged**
