### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by konsumlamm**
Fixes formatting in `Data.IntMap`/`Data.IntSet` (and related modules).
Due to a line break, the text in quotes was not cursive in the docs, which is fixed by removing the line break.

### CODE REVIEW

**Review by sjakobi — APPROVED** [review]
Thanks! This looks like a bug in haddock to me. Do you know whether it has been reported already?

**Comment by treeowl** [comment]
Is there another way to break these lines while preserving the formatting? I'll take this if it's the best we can get.

**Comment by konsumlamm** [comment]
> Thanks! This looks like a bug in haddock to me. Do you know whether it has been reported already?

I found https://github.com/haskell/haddock/issues/126, which comes to the conclusion that it's not worth it.

> Is there another way to break these lines while preserving the formatting? I'll take this if it's the best we can get.

One could write
```hs
--    * D.R. Morrison,
--      \"/PATRICIA -- Practical Algorithm To Retrieve Information Coded In Alphanumeric/\",
--      Journal of the ACM, 15(4), October 1968, pages 514-534.
```
but I haven't found any way to escape the line break.

**Comment by konsumlamm** [comment]
ping @treeowl

**Comment by treeowl** [comment]
Thanks.

**Pull request merged**
