### PR TITLE
Use countTrailingZeros for indexOfTheOnlyBit

### PR DESCRIPTION
**Pull request by alexbiehl**
This is an experiment for `indexOfTheOnlyBit`. I haven't benchmarked yet. But will do so tonight.

### CODE REVIEW

**Comment by treeowl** [comment]
@alexbiehl, what's with the regressions in list conversion functions?

**Comment by treeowl** [comment]
I'm sorry I lost track of this. The benchmark numbers you posted look very good, but unfortunately I haven't been able to reproduce your results. Part of the problem may be the general flakiness of the incredibly short benchmarks. Can you suggest a procedure for getting good results reliably?

**Comment by alexbiehl** [comment]
Me neither! I went ahead and further "optimized" the folds by using Count{Leading, Trailing}Zeros but the effect was basically nil. I suggest we abandon this for now.

**Comment by treeowl** [comment]
All right. Let me know. We could use more reliable benchmarks regardless of what happens to this PR.

**Comment by treeowl** [comment]
Do you think you could rebase this? @Fuuzetsu did some benchmarking and found that it at least doesn't seem to hurt. It's definitely less messy and cuts code size in key places.

**Comment by alexbiehl** [comment]
Yeah sure, will do this week.

**Comment by alexbiehl** [comment]
@treeowl Done!

**Comment by treeowl** [comment]
Thanks!

**Pull request merged**
