### PR TITLE
Merge 0.7

### PR DESCRIPTION
**Pull request by treeowl**

### CODE REVIEW

**Comment by meooow25** [comment]
```
Resolving dependencies...
Error: cabal-3.10.2.0: Could not resolve dependencies:
[__0] trying: containers-0.7 (user goal)
[__1] trying: base-4.16.4.0/installed-4.16.4.0 (dependency of containers)
[__2] trying: containers-tests-0 (user goal)
[__3] trying: nothunks-0.2.1.0 (dependency of containers-tests)
[__4] next goal: ghc-heap (dependency of nothunks)
[__4] rejecting: ghc-heap-9.2.8/installed-9.2.8 (conflict: containers==0.7, ghc-heap => containers==0.6.5.1/installed-0.6.5.1)
[__4] rejecting: ghc-heap-9.8.1 (conflict: containers==0.7, ghc-heap => containers>=0.6.2.1 && <0.7)
[__4] skipping: ghc-heap-9.6.3, ghc-heap-9.6.1, ghc-heap-9.4.1, ghc-heap-9.2.2, ghc-heap-9.2.1 (has the same characteristics that caused the previous version to fail: excludes 'containers' version 0.7)
[__4] rejecting: ghc-heap-9.0.1 (conflict: base => ghc-prim==0.8.0/installed-0.8.0, ghc-heap => ghc-prim>0.2 && <0.8)
[__4] fail (backjumping, conflict set: base, containers, ghc-heap, nothunks)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: containers, base, ghc-heap, nothunks, containers-tests
```

@treeowl from the logs the failure seems to be because `ghc-heap` does not allow `containers-0.7`:
https://hackage.haskell.org/package/ghc-heap

**Comment by treeowl** [comment]
Thanks, @meooow25 . @bgamari , is this just a matter of bumping the Hackage bounds for `ghc-heap`?

**Comment by Bodigrim** [comment]
To speed things up I made a revision: https://hackage.haskell.org/package/ghc-heap-9.8.1/revisions/

Now fc3a61a passes CI: https://github.com/haskell/containers/actions/runs/8198216367/job/22485297613

@treeowl I think you can revert changes to CI in 5f8b8a2 and go ahead with a merge.

**Comment by treeowl** [comment]
Thanks.

**Pull request merged**
